name: dosely
description: "A Smart Medication Analysis System Using AI and Patient Medical History"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  
  # Core & State
  provider: ^6.1.2
  
  # UI & Utils
  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.1
  country_picker: ^2.0.27
  intl: ^0.20.2
  fluttertoast: ^8.2.8
  
  # Medicine Identification Engine
  camera: ^0.10.6
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.13.0
  http: ^1.2.2
  shared_preferences: ^2.3.0
  
  # Firebase (Auth + Firestore for profiles & history)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/dosely_logo.png
    # Add more later:
    # - assets/images/scan_background.png
    # - assets/images/pillo_avatar.png