// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ_FUCYzXVDGEAQP4D9KLOjFhgjT56lZ8',
    appId: '1:644937207033:web:b23fc45660fdcf40ab6628',
    messagingSenderId: '644937207033',
    projectId: 'dosley-76bd1',
    authDomain: 'dosley-76bd1.firebaseapp.com',
    storageBucket: 'dosley-76bd1.firebasestorage.app',
    measurementId: 'G-414PWT97XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgZbmZovaHQXVH9hfy8wYjXqIbwVS7VJo',
    appId: '1:644937207033:android:43125812846c5f2eab6628',
    messagingSenderId: '644937207033',
    projectId: 'dosley-76bd1',
    storageBucket: 'dosley-76bd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPKrEBzKFqKkhAw-TQRHKwRy_yvjYphAk',
    appId: '1:644937207033:ios:6d853ce3f8b3e9ebab6628',
    messagingSenderId: '644937207033',
    projectId: 'dosley-76bd1',
    storageBucket: 'dosley-76bd1.firebasestorage.app',
    iosBundleId: 'com.example.healthscanai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPKrEBzKFqKkhAw-TQRHKwRy_yvjYphAk',
    appId: '1:644937207033:ios:6d853ce3f8b3e9ebab6628',
    messagingSenderId: '644937207033',
    projectId: 'dosley-76bd1',
    storageBucket: 'dosley-76bd1.firebasestorage.app',
    iosBundleId: 'com.example.healthscanai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ_FUCYzXVDGEAQP4D9KLOjFhgjT56lZ8',
    appId: '1:644937207033:web:af2b8e828a9d80bfab6628',
    messagingSenderId: '644937207033',
    projectId: 'dosley-76bd1',
    authDomain: 'dosley-76bd1.firebaseapp.com',
    storageBucket: 'dosley-76bd1.firebasestorage.app',
    measurementId: 'G-H30MKWDM18',
  );
}
